{{- /*
SPDX-License-Identifier: Apache-2.0
*/}}

{{ if .Values.kubepromstack.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hedera-block-node.fullname" . }}-grafana-datasource
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |
    apiVersion: 2
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://{{ .Release.Name }}-kubepromstack-prometheus:9090
        isDefault: true
        editable: true
        jsonData:
          timeInterval: "15s"
          
    {{- if .Values.loki.enabled }}
      - name: Loki
        type: loki
        url: http://{{ .Release.Name }}-loki:3100
        access: proxy
        isDefault: false
        editable: true
    {{- end }}

{{- end }}
